name: signature_pad
author: John Ryan <john.p.ryan4@gmail.com>
description: A flutter and HTML 5 canvas signature library
version: 2.1.0
homepage: https://github.com/johnpryan/signature-pad-dart
dependencies:
  stream_transform: ^1.1.0
dev_dependencies:
  build_runner: any
  build_web_compilers: any
environment:
  sdk: '>=1.24.3 <3.0.0'
