name: signature_pad_flutter
description: Flutter package for signature_pad
version: 1.3.0
author: John Ryan <john.p.ryan4@gmail.com>
homepage: https://github.com/johnpryan/signature-pad-dart

dependencies:
  flutter:
    sdk: flutter
  stream_transform: ^1.1.0

dev_dependencies:
  test: ^1.12.0

environment:
  sdk: '>=2.3.0 <3.0.0'

flutter:
